[package]
name = "groth16_example_bn254"
version = "0.1.0"
edition = "2024_07"

[dependencies]
garaga = { path = "../../" }
starknet = "2.11.2"

[cairo]
sierra-replace-ids = false

[dev-dependencies]
cairo_test = "2.11.2"

[[target.starknet-contract]]
casm = true
casm-add-pythonic-hints = true
