import asyncio
import os
from enum import Enum
from pathlib import Path

import dotenv
from starknet_py.net.account.account import Account
from starknet_py.net.full_node_client import FullNodeClient
from starknet_py.net.models import StarknetChainId
from starknet_py.net.signer.stark_curve_signer import KeyPair

from garaga.hints.io import to_int
from garaga.starknet.cli.smart_contract_project import SmartContractProject
from garaga.starknet.tests_and_calldata_generators.drand_calldata import (
    generate_drand_decrypt_constants,
)

dotenv.load_dotenv(".secrets")

CONTRACTS_PATH = Path("src/contracts")


class Network(Enum):
    SEPOLIA = "sepolia"
    MAINNET = "mainnet"

    def to_starknet_chain_id(self):
        if self == Network.SEPOLIA:
            return StarknetChainId.SEPOLIA
        elif self == Network.MAINNET:
            return StarknetChainId.MAINNET
        else:
            raise ValueError(f"Unknown network: {self}")


def get_account(network: Network):
    rpc_url = os.getenv(f"{network.value.upper()}_RPC_URL")
    account_address = os.getenv(f"{network.value.upper()}_ACCOUNT_ADDRESS")
    account_private_key = os.getenv(f"{network.value.upper()}_ACCOUNT_PRIVATE_KEY")

    client = FullNodeClient(node_url=rpc_url)
    account = Account(
        address=account_address,
        client=client,
        key_pair=KeyPair.from_private_key(to_int(account_private_key)),
        chain=network.to_starknet_chain_id(),
    )
    return account


async def declare_contract_from_path(path: Path, network: Network):
    contract = SmartContractProject(smart_contract_folder=path)
    account = get_account(network)
    await contract.declare_class_hash(account=account)


async def declare_contract_from_path_both_networks(path: Path):
    await declare_contract_from_path(path, Network.SEPOLIA)
    await declare_contract_from_path(path, Network.MAINNET)


if __name__ == "__main__":
    asyncio.run(
        declare_contract_from_path_both_networks(CONTRACTS_PATH / "universal_ecip")
    )
    asyncio.run(
        declare_contract_from_path_both_networks(CONTRACTS_PATH / "drand_quicknet")
    )

    # Generate verifier class hash into decrypt constants, then declare
    verifier = SmartContractProject(
        smart_contract_folder=CONTRACTS_PATH / "drand_quicknet"
    )
    generate_drand_decrypt_constants(
        verifier.get_sierra_class_hash(),
        CONTRACTS_PATH / "drand_decrypt_quicknet",
    )
    asyncio.run(
        declare_contract_from_path_both_networks(
            CONTRACTS_PATH / "drand_decrypt_quicknet"
        )
    )

    asyncio.run(
        declare_contract_from_path_both_networks(
            CONTRACTS_PATH / "autogenerated" / "risc0_verifier_bn254"
        )
    )
    asyncio.run(
        declare_contract_from_path_both_networks(
            CONTRACTS_PATH / "autogenerated" / "sp1_verifier_bn254"
        )
    )
