import asyncio
import os
from enum import Enum
from pathlib import Path

import dotenv
from starknet_py.net.account.account import Account
from starknet_py.net.full_node_client import FullNodeClient
from starknet_py.net.models import StarknetChainId
from starknet_py.net.signer.stark_curve_signer import KeyPair

from garaga.hints.io import to_int
from garaga.starknet.cli.smart_contract_project import SmartContractProject

dotenv.load_dotenv(".secrets")

CONTRACTS_PATH = Path("src/contracts")


class Network(Enum):
    SEPOLIA = "sepolia"
    MAINNET = "mainnet"

    def to_starknet_chain_id(self):
        if self == Network.SEPOLIA:
            return StarknetChainId.SEPOLIA
        elif self == Network.MAINNET:
            return StarknetChainId.MAINNET
        else:
            raise ValueError(f"Unknown network: {self}")


def get_account(network: Network):
    rpc_url = os.getenv(f"{network.value.upper()}_RPC_URL")
    account_address = os.getenv(f"{network.value.upper()}_ACCOUNT_ADDRESS")
    account_private_key = os.getenv(f"{network.value.upper()}_ACCOUNT_PRIVATE_KEY")

    client = FullNodeClient(node_url=rpc_url)
    account = Account(
        address=account_address,
        client=client,
        key_pair=KeyPair.from_private_key(to_int(account_private_key)),
        chain=network.to_starknet_chain_id(),
    )
    return account


async def declare_contract_from_path(path: Path, network: Network):
    contract = SmartContractProject(smart_contract_folder=path)
    account = get_account(network)
    await contract.declare_class_hash(account=account)


async def declare_contract_from_path_both_networks(path: Path):
    await declare_contract_from_path(path, Network.SEPOLIA)
    await declare_contract_from_path(path, Network.MAINNET)


def generate_drand_decrypt_constants(verifier_path: Path, decrypt_path: Path):
    """Compute the verifier's sierra class hash and write it to the decrypt constants file."""
    verifier = SmartContractProject(smart_contract_folder=verifier_path)
    class_hash = verifier.get_sierra_class_hash()
    constants_file = decrypt_path / "src" / "drand_decrypt_constants.cairo"
    constants_file.write_text(
        f"// Generated by declare_maintained_contracts.py — do not edit manually.\n"
        f"pub const VERIFIER_CLASS_HASH: felt252 = {hex(class_hash)};\n"
    )
    print(f"Generated {constants_file} with VERIFIER_CLASS_HASH = {hex(class_hash)}")


if __name__ == "__main__":
    asyncio.run(
        declare_contract_from_path_both_networks(CONTRACTS_PATH / "universal_ecip")
    )
    asyncio.run(
        declare_contract_from_path_both_networks(CONTRACTS_PATH / "drand_quicknet")
    )

    # Generate verifier class hash into decrypt constants, then declare
    generate_drand_decrypt_constants(
        CONTRACTS_PATH / "drand_quicknet",
        CONTRACTS_PATH / "drand_decrypt_quicknet",
    )
    asyncio.run(
        declare_contract_from_path_both_networks(
            CONTRACTS_PATH / "drand_decrypt_quicknet"
        )
    )

    asyncio.run(
        declare_contract_from_path_both_networks(
            CONTRACTS_PATH / "autogenerated" / "risc0_verifier_bn254"
        )
    )
    asyncio.run(
        declare_contract_from_path_both_networks(
            CONTRACTS_PATH / "autogenerated" / "sp1_verifier_bn254"
        )
    )
