[project]
protostar-version = "0.12.0"
lib-path = "contracts/lib"
cairo-path = [
    "contracts/lib/cairo_contracts/src",
    "src",
]

[contracts]
bn254 = ["contracts/cairo_bn254/bn254_precompiles.cairo"]

