# This file (along with Dockerfile) helps createing reproducible builds
# Usage: docker compose up --build && docker compose down

services:
  app:
    build: .
    volumes:
      - "../../..:/garaga"
