
[package]
name = "groth16_example_bn254"
version = "0.1.0"
edition = "2024_07"

[dependencies]
garaga = { path = "../../" }
starknet = "2.7.0"

[cairo]
sierra-replace-ids = false

[[target.starknet-contract]]
casm = true
casm-add-pythonic-hints = true
