# This file (along with Dockerfile) helps creating reproducible builds
# - It must be manually triggered whenever the Rust code is changed
# - It will update the code generated under src/wasm/pkg
# Usage: docker compose up --build && docker compose down

services:
  app:
    platform: linux/amd64
    build: .
    volumes:
      - "../../..:/garaga"
