#!/bin/bash
set -e

clean_dirs() {
    rm -rf src/src/circuits/*.cairo
    rm -rf src/contracts/autogenerated/*
}

run_generators() {
    python hydra/garaga/starknet/honk_contract_generator/generator_honk.py
    python hydra/garaga/precompiled_circuits/all_circuits.py
    python hydra/garaga/starknet/groth16_contract_generator/generator.py
    python hydra/garaga/starknet/groth16_contract_generator/generator_risc0.py
    python hydra/garaga/starknet/groth16_contract_generator/generator_sp1.py
}

clean_dirs

start_time=$(date +%s)

if [ "$1" = "no-tests" ]; then
    run_generators
else
    rm -rf src/src/tests/autogenerated/*
    run_generators
    python hydra/garaga/starknet/tests_and_calldata_generators/test_writer.py
fi

elapsed=$(($(date +%s) - start_time))
echo "Total time taken: ${elapsed} seconds"
