#!/usr/bin/env bash

# Script to run snforge test in all autogenerated contract folders
# Usage: ./tools/make/test_contracts.sh

set -e

# Get the directory where this script is located
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
# Get the repository root (two levels up from script location)
REPO_ROOT="$(cd "$SCRIPT_DIR/../.." && pwd)"

# Path to autogenerated contracts
AUTOGEN_DIR="$REPO_ROOT/src/contracts/autogenerated"

# Check if the autogenerated directory exists
if [ ! -d "$AUTOGEN_DIR" ]; then
    echo "Error: Autogenerated directory not found at $AUTOGEN_DIR"
    exit 1
fi

echo "Running snforge test in all autogenerated contract folders..."
echo "========================================================"
echo ""

# Track success/failure
FAILED_TESTS=()
PASSED_TESTS=()

# Iterate through each subdirectory in autogenerated
for dir in "$AUTOGEN_DIR"/*/ ; do
    if [ -d "$dir" ]; then
        folder_name=$(basename "$dir")
        echo "Testing: $folder_name"
        echo "----------------------------------------"

        # Change to the directory and run snforge test
        if (cd "$dir" && snforge test); then
            PASSED_TESTS+=("$folder_name")
            echo "✓ $folder_name: PASSED"
        else
            FAILED_TESTS+=("$folder_name")
            echo "✗ $folder_name: FAILED"
        fi

        echo ""
    fi
done

# Print summary
echo "========================================================"
echo "Test Summary"
echo "========================================================"
echo "Passed: ${#PASSED_TESTS[@]}"
for test in "${PASSED_TESTS[@]}"; do
    echo "  ✓ $test"
done

if [ ${#FAILED_TESTS[@]} -gt 0 ]; then
    echo ""
    echo "Failed: ${#FAILED_TESTS[@]}"
    for test in "${FAILED_TESTS[@]}"; do
        echo "  ✗ $test"
    done
    exit 1
else
    echo ""
    echo "All tests passed!"
    exit 0
fi
