#!/bin/bash
set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(cd "$SCRIPT_DIR/../.." && pwd)"
RISC0_VERIFIER_DIR="$PROJECT_ROOT/src/contracts/autogenerated/risc0_verifier_bn254"
FIBONACCI_SEQUENCER_FILE="$PROJECT_ROOT/src/contracts/risc0_sample_app/fibonacci_sequencer/src/lib.cairo"

echo "Computing class hash for Risc0Groth16VerifierBN254..."
OUTPUT=$(cd "$RISC0_VERIFIER_DIR" && sncast utils class-hash --contract-name Risc0Groth16VerifierBN254)

CLASS_HASH=$(echo "$OUTPUT" | grep "Class Hash:" | awk '{print $3}')
if [ -z "$CLASS_HASH" ]; then
    echo "Error: Could not parse class hash from sncast output: $OUTPUT"
    exit 1
fi

# Strip leading zeros for Cairo format (0x0708... -> 0x708...)
CAIRO_CLASS_HASH=$(echo "$CLASS_HASH" | sed 's/^0x0*/0x/')
echo "Class hash: $CAIRO_CLASS_HASH"

# Portable sed -i (macOS requires '' suffix, Linux does not)
sed -i.bak "s|^\([[:space:]]*\)0x[0-9a-fA-F]\{1,64\};|\1$CAIRO_CLASS_HASH;|" "$FIBONACCI_SEQUENCER_FILE"
rm -f "${FIBONACCI_SEQUENCER_FILE}.bak"

scarb fmt "$FIBONACCI_SEQUENCER_FILE"
echo "Updated RISC_ZERO_VERIFIER_CLASS_HASH in fibonacci_sequencer."
