#!/bin/bash
set -e

# Directory paths
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(cd "$SCRIPT_DIR/../.." && pwd)"
RISC0_VERIFIER_DIR="$PROJECT_ROOT/src/contracts/autogenerated/risc0_verifier_bn254"
FIBONACCI_SEQUENCER_FILE="$PROJECT_ROOT/src/contracts/risc0_sample_app/fibonacci_sequencer/src/lib.cairo"

echo "Computing class hash for Risc0Groth16VerifierBN254..."

# Run sncast to get the class hash
OUTPUT=$(cd "$RISC0_VERIFIER_DIR" && sncast utils class-hash --contract-name Risc0Groth16VerifierBN254)

# Parse the class hash from the output (format: "Class Hash: 0x...")
CLASS_HASH=$(echo "$OUTPUT" | grep "Class Hash:" | awk '{print $3}')

if [ -z "$CLASS_HASH" ]; then
    echo "Error: Could not parse class hash from sncast output"
    echo "Output was: $OUTPUT"
    exit 1
fi

echo "Parsed class hash: $CLASS_HASH"

# Remove leading zeros after 0x for Cairo format (0x0708... -> 0x708...)
CAIRO_CLASS_HASH=$(echo "$CLASS_HASH" | sed 's/^0x0*/0x/')

echo "Cairo format class hash: $CAIRO_CLASS_HASH"

# Update the class hash in the fibonacci sequencer contract
if [ ! -f "$FIBONACCI_SEQUENCER_FILE" ]; then
    echo "Error: Fibonacci sequencer file not found at $FIBONACCI_SEQUENCER_FILE"
    exit 1
fi

# Replace the class hash value in the Cairo file
# Match a line that contains only whitespace followed by a 64-char hex value and semicolon
sed -i "s/^\([[:space:]]*\)0x[0-9a-fA-F]\{63,64\};/\1$CAIRO_CLASS_HASH;/" "$FIBONACCI_SEQUENCER_FILE"

echo "Updated RISC_ZERO_VERIFIER_CLASS_HASH in $FIBONACCI_SEQUENCER_FILE"

# Format the Cairo file
echo "Formatting $FIBONACCI_SEQUENCER_FILE..."
scarb fmt "$FIBONACCI_SEQUENCER_FILE"

echo "Done."
