[package]
name = "drand_decrypt_quicknet"
version = "0.1.0"
edition = "2024_07"

[dependencies]
garaga = { path = "../.." }
drand_quicknet = { path = "../drand_quicknet" }
starknet = "2.16.1"

[cairo]
sierra-replace-ids = false

[[target.starknet-contract]]
casm = true
casm-add-pythonic-hints = true
