leaf_index = "2"
leaf_premiage = "0"
num_leafs = "5"
peaks = ["0x1069673dcdb12263df301a6ff584a7ec261a44cb9dc68df067a4774460b1f1e1", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0"]
root_hash = "0x1ba30aaf15c7694786a1f118ca39fcc6c997b48da9dfa62e9ec3e83ac7d6304d"

[proof]
len = "2"

[[proof.storage]]
hash = "0"

[[proof.storage]]
hash = "0x2098f5fb9e239eab3ceac3f27b81e481dc3124d55ffed523a839ee8446b64864"

[[proof.storage]]
hash = "0"

[[proof.storage]]
hash = "0"

[[proof.storage]]
hash = "0"

[[proof.storage]]
hash = "0"

[[proof.storage]]
hash = "0"

[[proof.storage]]
hash = "0"

[[proof.storage]]
hash = "0"

[[proof.storage]]
hash = "0"

[[proof.storage]]
hash = "0"

[[proof.storage]]
hash = "0"

[[proof.storage]]
hash = "0"

[[proof.storage]]
hash = "0"

[[proof.storage]]
hash = "0"

[[proof.storage]]
hash = "0"

[[proof.storage]]
hash = "0"

[[proof.storage]]
hash = "0"

[[proof.storage]]
hash = "0"

[[proof.storage]]
hash = "0"

[[proof.storage]]
hash = "0"

[[proof.storage]]
hash = "0"

[[proof.storage]]
hash = "0"

[[proof.storage]]
hash = "0"

[[proof.storage]]
hash = "0"

[[proof.storage]]
hash = "0"

[[proof.storage]]
hash = "0"

[[proof.storage]]
hash = "0"

[[proof.storage]]
hash = "0"

[[proof.storage]]
hash = "0"

[[proof.storage]]
hash = "0"

[[proof.storage]]
hash = "0"
