import { G1Point } from "../../definitions";

export enum HonkFlavor {
    KECCAK = 0,
    STARKNET = 1,
}

export interface HonkProof {
    circuit_size: number,
    public_inputs_size: number,
    public_inputs_offset: number,
    public_inputs: bigint[],
    w1: G1Point,
    w2: G1Point,
    w3: G1Point,
    w4: G1Point,
    z_perm: G1Point,
    lookup_read_counts: G1Point,
    lookup_read_tags: G1Point,
    lookup_inverses: G1Point,
    sumcheck_univariates: bigint[][],
    sumcheck_evaluations: bigint[],
    gemini_fold_comms: G1Point[],
    gemini_a_evaluations: bigint[],
    shplonk_q: G1Point,
    kzg_quotient: G1Point,
}

export interface HonkVerifyingKey {
    circuit_size: number,
    log_circuit_size: number,
    public_inputs_size: number,
    public_inputs_offset: number,
    qm: G1Point,
    qc: G1Point,
    ql: G1Point,
    qr: G1Point,
    qo: G1Point,
    q4: G1Point,
    q_arith: G1Point,
    q_delta_range: G1Point,
    q_elliptic: G1Point,
    q_aux: G1Point,
    q_lookup: G1Point,
    q_poseidon2_external: G1Point,
    q_poseidon2_internal: G1Point,
    s1: G1Point,
    s2: G1Point,
    s3: G1Point,
    s4: G1Point,
    id1: G1Point,
    id2: G1Point,
    id3: G1Point,
    id4: G1Point,
    t1: G1Point,
    t2: G1Point,
    t3: G1Point,
    t4: G1Point,
    lagrange_first: G1Point,
    lagrange_last: G1Point,
}
