// import { G1Point } from "../../definitions";

export enum HonkFlavor {
    KECCAK = 0,
    STARKNET = 1,
}

// export interface HonkProof {
//     publicInputs: bigint[],
//     w1: G1Point,
//     w2: G1Point,
//     w3: G1Point,
//     w4: G1Point,
//     zPerm: G1Point,
//     lookupReadCounts: G1Point,
//     lookupReadTags: G1Point,
//     lookupInverses: G1Point,
//     sumcheckUnivariates: bigint[], // flattened
//     sumcheckEvaluations: bigint[],
//     geminiFoldComms: G1Point[],
//     geminiAEvaluations: bigint[],
//     shplonkQ: G1Point,
//     kzgQuotient: G1Point,
// }

// export interface ZKHonkProof {
//     publicInputs: bigint[],
//     w1: G1Point,
//     w2: G1Point,
//     w3: G1Point,
//     w4: G1Point,
//     zPerm: G1Point,
//     lookupReadCounts: G1Point,
//     lookupReadTags: G1Point,
//     lookupInverses: G1Point,
//     libraCommitments: G1Point[],
//     libraSum: bigint,
//     sumcheckUnivariates: bigint[], // flattened
//     sumcheckEvaluations: bigint[],
//     libraEvaluation: bigint,
//     geminiMaskingPoly: G1Point,
//     geminiMaskingEval: bigint,
//     geminiFoldComms: G1Point[],
//     geminiAEvaluations: bigint[],
//     libraPolyEvals: bigint[],
//     shplonkQ: G1Point,
//     kzgQuotient: G1Point,
// }

// export interface HonkVerifyingKey {
//     circuitSize: number,
//     logCircuitSize: number,
//     publicInputsSize: number,
//     publicInputsOffset: number,
//     qm: G1Point,
//     qc: G1Point,
//     ql: G1Point,
//     qr: G1Point,
//     qo: G1Point,
//     q4: G1Point,
//     qLookup: G1Point,
//     qArith: G1Point,
//     qDeltaRange: G1Point,
//     qElliptic: G1Point,
//     qAux: G1Point,
//     qPoseidon2External: G1Point,
//     qPoseidon2Internal: G1Point,
//     s1: G1Point,
//     s2: G1Point,
//     s3: G1Point,
//     s4: G1Point,
//     id1: G1Point,
//     id2: G1Point,
//     id3: G1Point,
//     id4: G1Point,
//     t1: G1Point,
//     t2: G1Point,
//     t3: G1Point,
//     t4: G1Point,
//     lagrangeFirst: G1Point,
//     lagrangeLast: G1Point,
// }
